# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build-app:
    docker:
      - image: circleci/python:3.6.7-stretch

    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint 
      - save_cache:
          paths:
            - ./
          key: app-build
  
  test-app:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-docker:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: build docker
          command: |
            docker build --tag=andtlopez/devops-capstone .
workflows:
  default:
    jobs:
      - build-app
      - test-app:
          requires: [build-app]
      - build-docker:
          requires: [test-app]